spring:
  application:
    name: charge-common
  data:
    # Redis配置
    redis:
      host: localhost
      port: 6379
      #      password: lew824927
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      timeout: 3000ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/charge_coupon_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lew824927
server:
  port: 8085